services:
  mongo-exforge:
    build:
      context: ./application
    container_name: mongo-exforge
    ports:
      - "3000:3000"
    env_file:
      - ./application/.env
    command: node dist/main.js
    restart: unless-stopped
